Feat/actual claw
Team-OKC-Robotics/FRC-2023 pull request #37
Opened 2023-01-28 19:07 UTC by X-EX3-X

for justin to check

2023-01-28 19:27 UTC, jkleiber requested changes
The bare bones are here, but we need to only include relevant code. Once the swerve branch gets merged, hopefully a lot of these file changes go away - we need to make sure this branch doesn't overwrite hard work done on other branches.

2023-01-28 19:27 UTC, jkleiber commented on src/main/cpp/IO/ClawIO.cpp
> +
Add `OKC_CHECK(hw_interface_->claw_open_and_close_encoder != nullptr);` here

2023-01-28 19:27 UTC, jkleiber commented on src/main/cpp/IO/ClawIO.cpp
> +    hw_interface_->claw_open_and_close_motor->Set (sw_interface_->claw_open_and_close_power);
why is there a space between `Set` and `(`

2023-01-28 19:27 UTC, jkleiber commented on src/main/cpp/subsystems/claw.cpp
> +
You need to at least put placeholder functions for `Periodic` and `SimulationPeriodic`

2023-01-28 19:27 UTC, jkleiber commented on src/main/include/Utils.h
> +
This file will conflict with master after #34. Please be careful as to not overwrite that change

2023-01-28 19:27 UTC, jkleiber commented on src/main/include/hardware/Actuators.h
> +#define TRIGGER_MOTOR 9
why are these copied in?

2023-01-28 19:27 UTC, jkleiber commented on src/main/include/hardware/Hardware.h
> +#include "io/ShooterIO.h"
These files don't exist, and should not be included

2023-01-28 19:27 UTC, jkleiber commented on src/main/include/hardware/Hardware.h
> +    std::unique_ptr<frc::DifferentialDrive> diff_drive;
This shouldn't be included

2023-01-28 19:27 UTC, jkleiber commented on src/main/include/hardware/Hardware.h
> +
Why is this here

2023-01-28 19:27 UTC, jkleiber commented on src/main/include/io/clawIO.h
> +#pragma once
This file needs to be named `ClawIO.h` not `clawIO.h`. Capitalize the file names

2023-01-28 19:27 UTC, jkleiber commented on src/main/include/io/clawIO.h
> +} ClawHardwareInterface;
Let's name this `ClawHardware`

2023-01-28 19:27 UTC, jkleiber commented on src/main/include/subsystems/claw.h
> +// Copyright (c) FIRST and other WPILib contributors.
This file should be `Claw.h` not `claw.h`. Capitalize file names

2023-02-21 16:06 UTC, jkleiber approved these changes
Looks good to me @X-EX3-X @danielbrownmsm  feel free to merge

2023-02-23 02:27 UTC, danielbrownmsm approved these changes
yeah we can merge. will need to add a lot of stuff, but this is a good skeleton

2023-02-23 02:27 UTC, danielbrownmsm commented on src/main/cpp/subsystems/Claw.cpp
> +    // SetPosition (50);//cube
I mean, really this PR has no functionality, but at least getting the framework is something

2023-02-23 02:27 UTC, merged