Arm improvement and tuning
Team-OKC-Robotics/FRC-2023 pull request #69
Opened 2023-03-28 00:14 UTC by deadlyvortex

Added feedforward to arm control.
Fixes #52

2023-03-30 12:08 UTC, danielbrownmsm requested changes
I'll go ahead and make these changes, but I'm leaving this review so Sai can see how the process works

2023-03-30 12:08 UTC, danielbrownmsm commented on src/main/cpp/subsystems/Arm.cpp
> +    double ff = TeamOKC::sign(this->desired_state_.rotation) * arm_kF_ * this->desired_state_.rotation * this->desired_state_.rotation;
add a comment about what this is actually doing

2023-03-30 12:08 UTC, danielbrownmsm commented on src/main/deploy/parameters.toml
>  extend_setpoint = 50.0
why is there another extend setpoint here?

2023-03-31 01:37 UTC, deadlyvortex commented
ok

2023-04-04 21:10 UTC, danielbrownmsm approved these changes
lgtm, and then we can merge the feat/GKC branch

2023-04-04 21:22 UTC, merged